# This ClassDefinition will be used to generate two CRDs:
# - SecureDatabaseClass: Spec will have fields named with `identifier` of each
#   resources below and their OpenAPIV3 validation schemas will be fetched from api-server.
#
# A controller will be spinned up to create the resources bind each of them to
# MySQLClaim directly.
apiVersion: crossplane.io/v1alpha1
kind: ClassDefinition
metadata:
  name: securedatabaseclasses.azure.example.org
spec:
  crdRef:
    # Assumes that a CRD with this name exists, otherwise will fail.
    name: mysqlinstances.database.example.org
  resources:
    # No actual config value is given here. Actual parameters will be given in
    # SecureDatabaseClass instances.
    #
    # Patches show the bindings from MySQLClaim to the actual resource
    # (ResourceGroup, MySQLServer etc.) directly, not using SecureDatabase as an
    # intermediary resource for field value propagation.
    #
    # If `fromFieldPath` refers to a field that doesn't exist in MySQLClaim, the
    # creation of this ResourceDefinition should fail.
    - identifier: resourcegroup
      apiVersion: azure.crossplane.io/v1alpha3
      kind: ResourceGroup
      patch:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.location"
          transforms:
            - type: map
              map:
                us-west: "West US"
                us-east: "East US"
    - identifier: mysqlserver
      apiVersion: database.azure.crossplane.io/v1beta1
      kind: MySQLServer
      patch:
        - fromFieldPath: "spec.storageGB"
          toFieldPath: "spec.forProvider.storageMB"
          transforms:
            - type: math
              math:
                multiply: 1024
      # Any resource can fill the keys with their connection secret, if there is one.
      connectionSecretKeys:
        - to: username # in claim's secret.
          from: username # in MySQLServer's secret.
        - to: password
          from: password
        - to: endpoint
          from: endpoint
    - identifier: vnetrule
      apiVersion: database.azure.crossplane.io/v1alpha3
      kind: MySQLServerVirtualNetworkRule