# Maybe ClaimDefinition(namespaced claims) and ResourceDefinition(cluster-scoped resource) would be separate so that we don't need features array.
apiVersion: crossplane.io/v1alpha1
kind: ClaimDefinition
metadata:
  name: mysqlclaims.database.example.org
spec:
  # these will be satisfied by the resource who'd like to bind to the claim.
  # no other keys will be propagated from the managed resource's secret.
  # app dev will know for sure that these are the correct name of the keys.
  connectionSecretKeys:
  - username
  - password
  - endpoint
  crdRef:
    name: mysqlclaims.database.example.org
  # This template is used to create a CRD (if crdRef is unset). Only a single
  # version is supported.
  crdSpecTemplate:
    group: database.example.org
    version: v1alpha1
    names:
      kind: MySQLClaim
      listKind: MySQLClaimList
      plural: mysqlclaims
      singular: mysqlclaim
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              engineVersion:
                enum:
                  - "5.6"
                  - "5.7"
                type: string
              storageGb:
                type: integer
              region:
                type: string
            type: object
        type: object