---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: securedatabases.azure.example.org
spec:
  group: azure.example.org
  names:
    kind: SecureDatabase
    listKind: SecureDatabaseList
    plural: securedatabases
    singular: securedatabase
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        administratorLogin:
          type: string
        location:
          type: string
        sslEnforcement:
          type: string
        version:
          type: string
        sku:
          properties:
            tier:
              type: string
            capacity:
              type: integer
            family:
              type: string
          type: object
        storageProfile:
          properties:
            storageMB:
              type: integer
          type: object
        virtualNetworkSubnetIdRef:
          properties:
            name:
              type: string
          type: object
        providerRef:
          properties:
            name:
              type: string
          type: object
      type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
