---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: securedatabases.azure.example.org
spec:
  group: azure.example.org
  names:
    kind: SecureDatabase
    listKind: SecureDatabaseList
    plural: securedatabases
    singular: securedatabase
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        resourcegroup:
          < Full Azure ResourceGroup CRD validation >
        mysqlserver:
          < Full Azure MySQLServer CRD validation >
        vnetrule:
          < Full MySQLServerVirtualNetworkRule CRD validation >
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
