apiVersion: crossplane.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: secure-mysql-server
spec:
  definitionRef:
    name: securedatabases.azure.example.org
  resources:
    - base:
        apiVersion: azure.crossplane.io/v1alpha3
        kind: ResourceGroup
        metadata:
        spec:
          location: West US
          providerRef:
            name: example
          reclaimPolicy: Delete
      patch:
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.providerRef.name"
        - fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.location"
    - base:
        apiVersion: database.azure.crossplane.io/v1beta1
        kind: MySQLServer
        spec:
          forProvider:
            administratorLogin: myadmin
            resourceGroupNameSelector:
              matchComposite: true
            location: West US
            sslEnforcement: Disabled
            version: "5.6"
            sku:
              tier: Basic
              capacity: 1
              family: Gen5
            storageProfile:
              storageMB: 20480
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerRef:
            name: example
          reclaimPolicy: Delete
      patch:
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.providerRef.name"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
        - fromFieldPath: "spec.version"
          toFieldPath: "spec.forProvider.version"
        - fromFieldPath: "spec.storageMB"
          toFieldPath: "spec.forProvider.storageMB"
        - fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.location"
      # Specifies how to map connection details from this primitive resource to
      # its composite resource. Only supported if corresponding ResourceDefinition
      # supports the connectable feature.
      connectionDetails:
        - name: username
          fromConnectionSecretKey: username
        - name: password
          fromConnectionSecretKey: password
        - name: endpoint
          fromConnectionSecretKey: endpoint
    - base:
        apiVersion: database.azure.crossplane.io/v1alpha3
        kind: MySQLServerVirtualNetworkRule
        spec:
          name: my-cool-vnet-rule
          serverNameSelector:
            matchComposite: true
          resourceGroupNameSelector:
            matchComposite: true
          properties:
            virtualNetworkSubnetIdRef:
              name: sample-subnet
          reclaimPolicy: Delete
          providerRef:
            name: azure-provider
      patch:
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.providerRef.name"
        - fromFieldPath: "spec.virtualNetworkSubnetIdRef.name"
          toFieldPath: "spec.properties.virtualNetworkSubnetIdRef.name"